/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface IProtocolFeesCollectorInterface extends ethers.utils.Interface {
  functions: {
    "getAuthorizer()": FunctionFragment;
    "getCollectedFeeAmounts(address[])": FunctionFragment;
    "getSwapFeePercentage()": FunctionFragment;
    "setSwapFeePercentage(uint256)": FunctionFragment;
    "vault()": FunctionFragment;
    "withdrawCollectedFees(address[],uint256[],address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getAuthorizer",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCollectedFeeAmounts",
    values: [string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getSwapFeePercentage",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setSwapFeePercentage",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "vault", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdrawCollectedFees",
    values: [string[], BigNumberish[], string]
  ): string;

  decodeFunctionResult(
    functionFragment: "getAuthorizer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCollectedFeeAmounts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSwapFeePercentage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSwapFeePercentage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vault", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawCollectedFees",
    data: BytesLike
  ): Result;

  events: {
    "SwapFeePercentageChanged(uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "SwapFeePercentageChanged"): EventFragment;
}

export type SwapFeePercentageChangedEvent = TypedEvent<
  [BigNumber] & { newSwapFeePercentage: BigNumber }
>;

export class IProtocolFeesCollector extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IProtocolFeesCollectorInterface;

  functions: {
    getAuthorizer(overrides?: CallOverrides): Promise<[string]>;

    getCollectedFeeAmounts(
      tokens: string[],
      overrides?: CallOverrides
    ): Promise<[BigNumber[]] & { feeAmounts: BigNumber[] }>;

    getSwapFeePercentage(overrides?: CallOverrides): Promise<[BigNumber]>;

    setSwapFeePercentage(
      newSwapFeePercentage: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    vault(overrides?: CallOverrides): Promise<[string]>;

    withdrawCollectedFees(
      tokens: string[],
      amounts: BigNumberish[],
      recipient: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  getAuthorizer(overrides?: CallOverrides): Promise<string>;

  getCollectedFeeAmounts(
    tokens: string[],
    overrides?: CallOverrides
  ): Promise<BigNumber[]>;

  getSwapFeePercentage(overrides?: CallOverrides): Promise<BigNumber>;

  setSwapFeePercentage(
    newSwapFeePercentage: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  vault(overrides?: CallOverrides): Promise<string>;

  withdrawCollectedFees(
    tokens: string[],
    amounts: BigNumberish[],
    recipient: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    getAuthorizer(overrides?: CallOverrides): Promise<string>;

    getCollectedFeeAmounts(
      tokens: string[],
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    getSwapFeePercentage(overrides?: CallOverrides): Promise<BigNumber>;

    setSwapFeePercentage(
      newSwapFeePercentage: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    vault(overrides?: CallOverrides): Promise<string>;

    withdrawCollectedFees(
      tokens: string[],
      amounts: BigNumberish[],
      recipient: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "SwapFeePercentageChanged(uint256)"(
      newSwapFeePercentage?: null
    ): TypedEventFilter<[BigNumber], { newSwapFeePercentage: BigNumber }>;

    SwapFeePercentageChanged(
      newSwapFeePercentage?: null
    ): TypedEventFilter<[BigNumber], { newSwapFeePercentage: BigNumber }>;
  };

  estimateGas: {
    getAuthorizer(overrides?: CallOverrides): Promise<BigNumber>;

    getCollectedFeeAmounts(
      tokens: string[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getSwapFeePercentage(overrides?: CallOverrides): Promise<BigNumber>;

    setSwapFeePercentage(
      newSwapFeePercentage: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    vault(overrides?: CallOverrides): Promise<BigNumber>;

    withdrawCollectedFees(
      tokens: string[],
      amounts: BigNumberish[],
      recipient: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getAuthorizer(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getCollectedFeeAmounts(
      tokens: string[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getSwapFeePercentage(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setSwapFeePercentage(
      newSwapFeePercentage: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    vault(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    withdrawCollectedFees(
      tokens: string[],
      amounts: BigNumberish[],
      recipient: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
